source 'https://rubygems.org'

gem 'redis'
gem 'activesupport'
gem 'foreman', '0.60.2'
gem 'dotenv'
gem 'mina', github: 'nadarei/mina'
gem 'chronic'
gem 'sentry-raven'
gem 'rest-client'
gem 'pry'
gem 'simon_web', :git => 'https://github.com/graves/simon_web'
